# Generated by Django 4.2.8 on 2026-06-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('date', models.CharField(blank=True, default='', max_length=20)),
                ('summary', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(default=list)),
                ('body', models.TextField(blank=True, default='')),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EducationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('period', models.CharField(blank=True, default='', max_length=100)),
                ('detail', models.CharField(blank=True, default='', max_length=300)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('period', models.CharField(blank=True, default='', max_length=100)),
                ('detail', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date', 'order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120)),
                ('title', models.CharField(default='', max_length=255)),
                ('affiliation', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('research_direction', models.TextField(blank=True, default='')),
                ('summary', models.TextField(blank=True, default='')),
                ('interests', models.JSONField(default=list)),
                ('link_github', models.URLField(blank=True, default='')),
                ('link_linkedin', models.URLField(blank=True, default='')),
                ('link_scholar', models.URLField(blank=True, default='')),
                ('link_cv', models.CharField(blank=True, default='/cv.pdf', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(default=list)),
                ('repo_url', models.URLField(blank=True, default='')),
                ('stars', models.IntegerField(blank=True, null=True)),
                ('highlight', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SkillGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=120)),
                ('items', models.JSONField(default=list)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
