# Generated by Django 4.2.8 on 2026-07-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('plugin', 'Plugin'), ('npx-package', 'npx package'), ('self-authored', 'Self-authored'), ('linked-project', 'Linked project')], max_length=20)),
                ('origin', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(choices=[('skill', 'Skill'), ('command', 'Command'), ('agent', 'Agent')], max_length=10)),
                ('tags', models.JSONField(default=list)),
                ('highlight_blurb', models.TextField(blank=True, default='')),
                ('highlight_order', models.IntegerField(blank=True, null=True)),
                ('published', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
