# Generated by Django 4.2.8 on 2026-07-03 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_agentskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentskill',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
