# Generated by Django 4.2.8 on 2026-07-03 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_agentskill_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentskill',
            name='usage',
            field=models.JSONField(default=list),
        ),
    ]
