# Generated by Django 4.2.8 on 2026-07-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_agentskill_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentskill',
            name='install_command',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='agentskill',
            name='workflow_category',
            field=models.CharField(blank=True, choices=[('literature', 'Literature & Research'), ('writing', 'Writing & Editing'), ('diagramming', 'Diagramming & Visualization'), ('slides', 'Slides & Posters'), ('web', 'Web & UI/UX'), ('engineering', 'Engineering & Agent Workflow')], default='', max_length=20),
        ),
    ]
