# Generated by Django 4.2.8 on 2026-06-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholar_id', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('authors', models.CharField(blank=True, default='', max_length=500)),
                ('venue', models.CharField(blank=True, default='', max_length=500)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('cited_by', models.IntegerField(default=0)),
                ('cited_by_url', models.URLField(blank=True, default='', max_length=500)),
                ('url', models.URLField(blank=True, default='', max_length=500)),
                ('core_rank', models.CharField(blank=True, default='', max_length=16)),
                ('core_acronym', models.CharField(blank=True, default='', max_length=32)),
                ('order_index', models.IntegerField(default=0)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-year', '-cited_by', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='ScholarProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('affiliation', models.CharField(blank=True, default='', max_length=255)),
                ('avatar_url', models.URLField(blank=True, default='', max_length=500)),
                ('citations_all', models.IntegerField(default=0)),
                ('h_index_all', models.IntegerField(default=0)),
                ('i10_index_all', models.IntegerField(default=0)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
