import { apiFetch, apiJson } from "./api";

export type StatsSummary = {
  totalViews: number;
  todayViews: number;
  uniqueVisitors: number;
};

// slug -> total views
export type BlogStats = Record<string, number>;

// Committed snapshot served by Vercel as a static asset (regenerated by the
// DB->fallback sync). Read when the backend is unreachable so counters degrade
// to the last-synced numbers instead of revealing an outage.
type StatsFallback = { summary: StatsSummary; blog: BlogStats };

async function readSnapshot<K extends keyof StatsFallback>(
  key: K,
  empty: StatsFallback[K],
): Promise<StatsFallback[K]> {
  try {
    const resp = await fetch("/fallback/stats.json", { cache: "force-cache" });
    if (!resp.ok) return empty;
    const data = (await resp.json()) as Partial<StatsFallback>;
    return (data?.[key] ?? empty) as StatsFallback[K];
  } catch {
    return empty;
  }
}

// Fire-and-forget page-view ping. `keepalive` lets it survive a navigation,
// and admin pages are never counted (the backend also skips the owner). When
// the backend is down this is a silent no-op — nothing to fall back to.
//
// Each path is counted at most once per browser session: bouncing back and
// forth between pages (or refreshing) no longer inflates the view count, while
// a genuine return visit — a new tab, or reopening after closing — counts
// again. sessionStorage is per-tab and cleared when the tab closes.
export function recordHit(path: string): void {
  if (path.startsWith("/admin")) return;
  try {
    const key = `viewed:${path}`;
    if (sessionStorage.getItem(key)) return;
    sessionStorage.setItem(key, "1");
  } catch {
    // sessionStorage blocked (private mode, etc.) — fall through and count.
  }
  void apiFetch("/api/stats/hit/", {
    method: "POST",
    body: JSON.stringify({ path }),
    keepalive: true,
  }).catch(() => {});
}

export async function getStatsSummary(): Promise<StatsSummary> {
  try {
    return await apiJson<StatsSummary>("/api/stats/summary/");
  } catch {
    return readSnapshot("summary", { totalViews: 0, todayViews: 0, uniqueVisitors: 0 });
  }
}

export async function getBlogStats(): Promise<BlogStats> {
  try {
    return await apiJson<BlogStats>("/api/stats/blog/");
  } catch {
    return readSnapshot("blog", {});
  }
}
