# Generated by Django 4.2.8 on 2026-06-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor', models.CharField(max_length=64, unique=True)),
                ('first_seen', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageViewDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=220)),
                ('day', models.DateField()),
                ('views', models.PositiveIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['path'], name='stats_pagev_path_7fe22a_idx')],
                'unique_together': {('path', 'day')},
            },
        ),
    ]
